version: 1.3.0_{build}
configuration: Release
platform: x64
install:
- cmd: git submodule update --init
before_build:
- cmd: nuget restore
build:
  project: PotatoWall.sln
  verbosity: minimal
image: Visual Studio 2022